name: Build and Test Pipeline
on: [push]
jobs: 
  Main:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🐙 Job triggered by ${{ github.event_name }} event."  
    - name: 🧺 Checkout Repository Code
      uses: actions/checkout@v2
    - name: 🛠 Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: 📦 Build with Maven
      run: mvn --batch-mode --update-snapshots test jacoco:report 
    - name: 🛠 Coverall Coverage Report Setup
      run: sed -i.bak 's/__coverall__repo__token__/${{ secrets.COVERALL_REPO_TOKEN }}/g' pom.xml
    - name: 🚀 Coverall Coverage Report Submission
      run: mvn coveralls:report
    - name: 🧹 Cleanup Repository Token
      if: ${{ always() }}
      run: if [ -f "pom.xml.bak" ]; then mv pom.xml.bak pom.xml; fi

